language: python
python:
  - "3.7"
install:
  - pip install -e .
script:
  - ./run_tests.sh
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  matrix:
    - PROXY_ZAKUPKI_HTTPS=127.0.0.1 PROXY_ZAKUPKI_HTTP=127.0.0.1
services:
  - postgresql
before_script:
  - cd migrations && ./up.sh && cd ..
